### ISSUE TITLE
Member score returning invalid scores even while logged in.

### ISSUE THREAD

**Issue by DeadlyEmbrace** [croberts22/umalapi#17]
It seems that some pages on MAL might still be using an older layout and as such the members_scores for older shows aren't populating correctly.
http://myanimelist.net/anime/11049 returns a members_score of null.
http://myanimelist.net/anime/28999/Charlotte returns the members_score correctly.

I dug around a bit but afraid my skills just aren't good enough to fix this, would you please look into this?

**Comment by croberts22** [comment]
Yep, I can, thanks for filing this.

**Comment by croberts22** [comment]
Right now, the temporary solution is to disable member scores on here until we figure out a better solution. It seems like there are issues with attaching the cookie onto the web requests, and it isn't honoring that as being logged in. Scores and episode/chapter counts are always being rendered as 0 (which is the default value if you aren't logged in).

Filing another ticket to get this resolved so we can obtain parity. For those using the API at the moment, I'm sorry for the inconvenience. I recommend using parts of the official API to get scores for the time being.
