### ISSUE TITLE
Rank is incorrect

### ISSUE THREAD

**Issue by seanblue** [croberts22/umalapi#29]
It looks like the rank is pulling in additional information, such as the superscript of '2'. Here are two examples that have bad data:
http://umal-api.coreyjustinroberts.com/1.1/anime/23281
http://umal-api.coreyjustinroberts.com/1.1/anime/4382

**Comment by croberts22** [comment]
It looks like the current query digs into the `div` tag, but it needs to go further into the new `span` tag:

current output: `"Ranked #2222Suzumiya Haruhi no Yuuutsu (2009)"`

solution returns: `"Ranked #2222"`

This'll be solved by using `'div[@id="contentWrapper"] > div > span'`.
