### ISSUE TITLE
Type is always showing up as "TV" or "Manga" (default values).

### ISSUE THREAD

**Issue by seanblue** [croberts22/umalapi#30]
For example:
http://myanimelist.net/anime/1689/Byousoku_5_Centimeter
http://umal-api.coreyjustinroberts.com/1.1/anime/1689

**Comment by croberts22** [comment]
Thanks for reporting this, I'll take a look at this over the weekend. 




On Thu, Jan 7, 2016 at 6:41 PM -0800, "seanblue" <notifications@github.com> wrote:












For example:

http://myanimelistnet/anime/1689/Byousoku_5_Centimeter

http://umal-apicoreyjustinrobertscom/11/anime/1689

**Comment by seanblue** [comment]
Just a reminder that this is still an issue.

**Comment by croberts22** [comment]
Hey @seanblue! Currently working on it. I have this fixed in the railgun repo, but didn't port it over here. I'll do that here in a few.
