### ISSUE TITLE
Migrate from Sinatra to Django

### ISSUE THREAD

**Issue by croberts22** [croberts22/umalapi#6]
This is a big project. I would like to move it to Django via Heroku for easier maintenance.

**Comment by DeadlyEmbrace** [comment]
I've created a copy of umalapi in C# that you can view [here](https://github.com/NinetailLabs/MAL.Net---A-.net-API-for-MAL)
You need a Windows machine to host it on, but the code itself is easy to maintain and extend (on average a breaking change takes around 15min - 1.5 hours to fix) The external API isn't 100% completed yet, but the data that it outputs is the same as umalapi.

At worst it might give you some ideas for modifying umalapi to help with maintanance.

**Comment by croberts22** [comment]
This is awesome man! I'll definitely take a look at it!

I've currently stalled on the idea in the hopes that MAL will keep their word and put out an updated API by the end of the year. That, and I've just been too busy to really get anything going right now.

**Comment by DeadlyEmbrace** [comment]
Would be really sweet if they gave us a proper API (just have to wonder if they'll expose all the data we want)
It's quite a pain having to fix an unofficial API every few days (if you even notice that it broke)

**Comment by croberts22** [comment]
Yeah, and a big issue is just how this API was created. It's difficult to test, and there's no nightly testing to get periodic updates on if things are working correctly. Scrapers of this kind definitely need this form of testing since anything can break at any time, unexpectedly. Let's just hope they deliver on their promise.
